apiVersion: schemas.schemahero.io/v1alpha4
kind: Table
metadata:
  name: session
  namespace: schemahero-tutorial
spec:
  database: test
  name: session
  schema:
    postgres:
      primaryKey:
      - id
      columns:
      - name: id
        type: text
        constraints:
          notNull: true
      - name: user_id
        type: text
        constraints:
          notNull: true
      - name: expire_at
        type: timestamp without time zone
        constraints:
          notNull: true
      - name: created_at
        type: timestamptz
        constraints:
          notNull: true
